fragment MyUser on User {
    id
    email
}

query Auth {
    auth {
        ...MyUser
    }
}

mutation Login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
        ...MyUser
    }
}
